version: "3.9"
services:
  discovery:
    image: consul:1.15
    ports:
      - 8500:8500

  serveur-conf:
    image: ghcr.io/laurich-app/serveur-conf:0.0.3

  postgres-utilisateur:
    image: postgres:12.17
    environment:
      - POSTGRES_DB=service-utilisateur
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pswd

  service-utilisateur:
    image: ghcr.io/laurich-app/service-utilisateur:1.1.0
    environment:
      - URL_CONFIG_SERVEUR=http://serveur-conf:8888
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - PRIVATE_KEY=app_pkcs8.prv
      - PUBLIC_KEY=app.pub
      - POSTGRES_URL=jdbc:postgresql://postgres-utilisateur:5432/service-utilisateur
      - POSTGRES_USER=user
      - POSTGRES_PSWD=pswd
    depends_on:
      - serveur-conf
      - discovery

  client:
    image: ghcr.io/laurich-app/client:0.0.1

  service-passerelle:
    build: .
    ports:
      - 8080:8080
    environment:
      - CLIENT_URL=http://client
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - DEBUG=true